apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-k8-demo
  template:
    metadata:
      labels:
        app: spring-k8-demo
    spec:
      containers:
        - name: spring-demo-k8-container
          image: docker.io/rajadocker2109/spring-k8-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
