apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-app
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: spring-k8-demo        # MUST match Service label
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http                # MUST match Service port name
      path: /actuator/prometheus
      interval: 15s
